services:
  - type: web
    name: hedera-token-analyzer-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
